# Generated by Django 4.0.6 on 2022-08-31 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0008_rename_profile_pic_userprofile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100, verbose_name='Айпи')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ip', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Айпи',
                'verbose_name_plural': 'Айпи пользователей',
            },
        ),
    ]
