# Generated by Django 4.0.6 on 2022-08-31 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0025_alter_article_views_count'),
        ('users', '0010_alter_ip_ip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ip',
        ),
    ]
