# Generated by Django 4.0.6 on 2022-09-24 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_notice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='user',
            new_name='user_to',
        ),
    ]
