# Generated by Django 4.0.6 on 2022-10-01 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_rename_user_notice_user_to'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
