# Generated by Django 4.0.6 on 2022-08-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_rename_image_article_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover_image',
            field=models.ImageField(upload_to='images/%Y/%m/%d/', verbose_name='Обложка'),
        ),
    ]
