# Generated by Django 4.0.6 on 2022-08-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_remove_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='comments_count',
            field=models.IntegerField(blank=True, default=0, verbose_name='Количество комментариев'),
        ),
        migrations.AlterField(
            model_name='article',
            name='views_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество просмотров'),
        ),
    ]
