# Generated by Django 4.0.6 on 2022-08-25 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_rename_username_article_author_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_published',
        ),
    ]
