# Generated by Django 4.0.6 on 2022-08-25 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_remove_comment_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='comments_count',
        ),
    ]
