# Generated by Django 4.0.6 on 2022-08-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_remove_article_comments_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='images/article_covers/%Y/%m/%d/', verbose_name='Обложка'),
        ),
    ]
