# Generated by Django 4.0.6 on 2022-08-31 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_ip'),
        ('articles', '0023_remove_article_views_count_article_views_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='views_count',
            field=models.ManyToManyField(blank=True, related_name='views', to='users.ip', verbose_name='Количество просмотров'),
        ),
    ]
