# Generated by Django 4.0.6 on 2022-08-31 08:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0024_alter_article_views_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='views_count',
            field=models.ManyToManyField(blank=True, related_name='views', to=settings.AUTH_USER_MODEL, verbose_name='Количество просмотров'),
        ),
    ]
