# Generated by Django 4.0.6 on 2022-09-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Публичный проект'),
        ),
    ]
