# Generated by Django 4.0.6 on 2022-09-11 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0026_alter_comment_options'),
        ('projects', '0004_project_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='articles.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(to='articles.tag', verbose_name='Тэги'),
        ),
    ]
