# Generated by Django 4.0.6 on 2022-09-20 04:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0015_application'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Application',
            new_name='ProjectApplication',
        ),
    ]
