# Generated by Django 4.0.6 on 2022-10-01 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_project_members'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectApplication',
        ),
    ]
